apiVersion: apps/v1
kind: Deployment
metadata:
  name: white
spec:
  selector:
    matchLabels:
      app: white
  template:
    metadata:
      labels:
        app: white
    spec:
      containers:
      - name: white
        image: kubedevio/web-nginx:white
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: white-service
spec:
  selector:
    app: white
  ports:
  - port: 80
    targetPort: 80  